"""
Fetches data from Google Sheets, updates shared/kpi-data.js,
and rebuilds all version bundles.

Usage (run from project root):
  python3 tools/refresh.py

Sheet credentials can be overridden via environment variables:
  SHEET_ID   — Google Sheets document ID
  SHEET_GID  — Sheet tab GID
"""
import os, csv, subprocess, sys
from io import StringIO
from datetime import datetime

try:
    import requests
except ImportError:
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'requests', '-q'])
    import requests

ROOT    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_JS = os.path.join(ROOT, 'shared', 'kpi-data.js')

SHEET_ID  = os.environ.get('SHEET_ID',  '1x1Ru8QhMzMkeQcnGHI3mCZ2zBI6twO4zFMeH21AMsNA')
SHEET_GID = os.environ.get('SHEET_GID', '475541063')

# ── Column name mapping ───────────────────────────────────────────────────────
# Keys = exact header names in the Google Sheet
# Change these if the sheet columns are renamed
COLS = {
    'date':  'Date',
    'lm':    'Volume Index',
    'eq':    'Active Units',
    'auto':  'Type A Output',
    'man':   'Type B Output',
    'tot':   'Total Output',
    'mob':   'App Sessions',
    'web':   'Web Sessions',
    'mau':   'Monthly Active',
}

def parse_num(s):
    s = s.strip()
    if not s or s.lower() == 'null':
        return None
    try:
        return int(float(s.replace(',', '')))
    except ValueError:
        return None

def fmt(v):
    return 'null' if v is None else str(v)

def format_date(s):
    """'Jan 7 2026' → "Jan 7 '26" """
    s = s.strip()
    for pattern in ('%b %d %Y', '%B %d %Y', '%b %d, %Y', '%B %d, %Y'):
        try:
            dt = datetime.strptime(s, pattern)
            return f"{dt.strftime('%b')} {dt.day} '{dt.strftime('%y')}"
        except ValueError:
            continue
    return s  # return as-is if unparseable

# ── Fetch ─────────────────────────────────────────────────────────────────────
url = (f"https://docs.google.com/spreadsheets/d/{SHEET_ID}"
       f"/export?format=csv&gid={SHEET_GID}")
print(f"Fetching sheet...")
resp = requests.get(url, timeout=15)
resp.raise_for_status()

reader = csv.DictReader(StringIO(resp.text))
rows   = []

for row in reader:
    date = row.get(COLS['date'], '').strip()
    if not date:
        continue

    lm   = parse_num(row.get(COLS['lm'],   ''))
    eq   = parse_num(row.get(COLS['eq'],   ''))
    auto = parse_num(row.get(COLS['auto'], ''))
    man  = parse_num(row.get(COLS['man'],  ''))
    tot  = parse_num(row.get(COLS['tot'],  ''))
    mob  = parse_num(row.get(COLS['mob'],  ''))
    web  = parse_num(row.get(COLS['web'],  ''))
    mau  = parse_num(row.get(COLS['mau'],  ''))

    # Skip fully empty rows
    if all(v is None for v in [lm, eq, auto, man, tot]):
        continue

    rows.append(
        f'  ["{format_date(date)}", {fmt(lm)}, {fmt(eq)}, '
        f'{fmt(auto)}, {fmt(man)}, {fmt(tot)}, '
        f'{fmt(mob)}, {fmt(web)}, {fmt(mau)}]'
    )

print(f"Parsed {len(rows)} rows")

# ── Write kpi-data.js ─────────────────────────────────────────────────────────
content  = '// Auto-generated by tools/refresh.py — do not edit manually\n'
content += '// [date, volumeIndex, activeUnits, typeA, typeB, total, app, web, monthlyActive]\n'
content += 'const RAW = [\n'
content += ',\n'.join(rows)
content += '\n];\n'

open(DATA_JS, 'w').write(content)
print(f"Written → shared/kpi-data.js")

# ── Rebuild bundles ───────────────────────────────────────────────────────────
bundle = os.path.join(ROOT, 'tools', 'bundle.py')
for version in ['v2-sections', 'v3-widgets']:
    print(f"Bundling {version}...")
    subprocess.run([sys.executable, bundle, version], cwd=ROOT, check=True)

print("\nDone — dist/ folders are ready.")
